name: Tectonic

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install mscgen
      run: wget -c https://www.mcternan.me.uk/mscgen/software/mscgen-static-0.20.tar.gz -O - | tar -xz
    - name: Install tectonic
      run: wget -c https://github.com/tectonic-typesetting/tectonic/releases/download/tectonic%400.8.0/tectonic-0.8.0-x86_64-unknown-linux-gnu.tar.gz -O - | tar -xz
    - name: Build PDF
      run: ./build_diagrams.sh && ./tectonic -X build
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
        branch: gh-pages
        folder: build/ProofOfLatency
        token: ${{ secrets.GH_PAT }}
