name: Tectonic

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get install libfontconfig1-dev libgraphite2-dev libharfbuzz-dev libicu-dev libssl-dev zlib1g-dev
    - name: Install tectonic
      run: cargo install tectonic
    - name: Build
      run: mkdir public && tectonic --outdir public Thesis.tex
      # Publish to gh-pages
    - uses: maxheld83/ghpages@v0.3.0
      env:
        BUILD_DIR: public/
        GH_PAT: ${{ secrets.GH_PAT }}
